version: '3'
services:
  nginx:
    container_name: nginx
    build: ./config/nginx
    volumes:
<<<<<<< HEAD
      - dbdata:/var/lib/mysql

  web:
    container_name: web
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      DATABASE_NAME: mysql
      DATABASE_USER: 'root'
      DATABASE_PASSWORD: mysql
      DATABASE_PORT: 3306
      DATABASE_HOST: db
      DJANGO_SETTINGS_MODULE: drinking_pleasure.dev
    restart: always
=======
      - .:/code
>>>>>>> 061d6269c0ef8736fc7f9f7b58f584685256bfa7
    ports:
      - "80:80"
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn drinking_pleasure.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000"