version: "3"
services:
  django-web:
    container_name: django-web
    image: mazle/mazle-test:1.0.0 # 이미지, 태그
    ports:
        - "8000:8000"
    build: ./
    volumes: 
        - ./:/home/ubuntu/Mazle/drinking_pleasure
        - ./log/uwsgi:/log
  nginx:
    container_name: nginx
    image: nginx
    ports:
        - "80:80"
    build: ./config/nginx
    volumes:
        - ./:/home/ubuntu/Mazle/drinking_pleasure
        - ./log/nginx:/log
    depends_on : 
        - django-web